### ISSUE TITLE
Adding and removing pages

### ISSUE THREAD

**Issue by smothers** [leecade/react-native-swiper#20]
Is there a way to add pages, like adding rows to a list view?

When I try to do this naively by rendering a new child view in the Swiper the new views all show up on the last page instead of creating new pages.

**Comment by sandcforge** [comment]
Here is my wordaround.
In render()
    let SwiperImage = this.state.imageUri.map((aUri, i) =>
        <View style={styles.imageSwiperFrame} title={<Text numberOfLines={1}></Text>}>
          <Image style={styles.imageSwiperImage} source={{uri: aUri}} />
        </View>
    );
you can update imageUri whenever you want.

Aslo you need to hack the code inside. because the total number of children(or images in this scenario) is  stored in this.state.total, which is not reactive to children. so in node_modules/react-native-swiper/dist/index.js 
  componentWillReceiveProps(props) {
    this.setState({total: props.children ? props.children.length || 1 : 0});
  },
this code is trying to update this.state.total whenever children is changed.

Thanks,
Chen

**Comment by nickmaxwell10** [comment]
@sandcforge that works!

**Comment by leecade** [comment]
try the new demo in `examples/examples/dynamic.js`
