### ISSUE TITLE
Partially view adjacent views

### ISSUE THREAD

**Issue by divyenduz** [leecade/react-native-swiper#299]
Is it possible to use this library and create partially visible swiper like 
<img width="205" alt="screen shot 2016-11-19 at 1 19 57 am" src="https://cloud.githubusercontent.com/assets/746482/20444257/5192f7ec-adf6-11e6-8358-9f54052cb28b.png">

**Comment by robbue** [comment]
`overflow: visible` on the `<Swiper>` component will get you started

```
<Swiper style={{overflow: 'visible'}} width={300}>
  ...
</Swiper>
```

**Comment by divyenduz** [comment]
I tried this out, it renders the component unusable. the swipe stops working. I think this is a bug.

**Comment by robbue** [comment]
It should not give you any errors. If so, what kind of errors do you get? I experienced that setting flex: 1 on the children elements could block swiping

**Comment by divyenduz** [comment]
Aha! It worked, this can be closed.
I had flex: 1 on children from the example in README.md

Regards,

**Comment by RubenSandwich** [comment]
I'm also looking into doing this.

One problem I'm running into is that this now makes it so that scrolling can only happen in the on the size of the supplied width prop, whereas I'd like scrolling to happen even if it starts on the partially visible views.

@divyenduz Did you run into this problem as well?

**Comment by divyenduz** [comment]
@RubenSandwich : Nope, I quit on it and moved out of react-native for now when not doing hobby stuff.

**Comment by dwilt** [comment]
I'm also looking into making this work. Having trouble.

**Comment by andrispraulitis** [comment]
Yes, you never gonna get it done as there is a little bug on swiper style. Basically the same style prop is added to scrollview as well as contentContainerStyle which makes no sense.

[https://github.com/leecade/react-native-swiper/blob/master/src/index.js#L551](url)
[https://github.com/leecade/react-native-swiper/blob/master/src/index.js#L553](url)

I think that contentContainerStyle should not include swiper style and also should be added before {...this.props} so you can have a swiper style as well as option to override contentContainerStyle.

Anyone else agree?

**Comment by andrispraulitis** [comment]
If I have control over each of those style properties it's totally doable, take a look at the screenshot.

<img width="321" alt="screen shot 2017-01-17 at 11 33 30" src="https://cloud.githubusercontent.com/assets/8721800/22018877/f1c5e46e-dca8-11e6-9166-7420fb35ff28.png">

**Comment by dwilt** [comment]
I put together a video showing how we got it working in our app: https://youtu.be/BG9Cxgylue0

**Comment by RubenSandwich** [comment]
@dwilt 

Thank you for commenting. Your solution hits a few problems that ultimately had my team make our own swiping component.

* The `overflow: 'visible'` currently only works on iOS, while overflow support just landed as an experimental feature for Android you have to sacrifice other things to use it: z-index, etc. See release notes [here](https://github.com/facebook/react-native/tree/master/ReactAndroid/src/main/java/com/facebook/react/flat).

* With the `overflow: 'visible'` solution the overflow, while shown, does not register touches on the gutters. So while this solution might be viable for large 'cards' it falls apart for small 'cards'.

Because both of those issues were deal breakers for our project. My team ended up creating our own swiper using a ScrollView with on iOS setting the snapToInterval to our card size and on Android firing an onScroll when the user finished scrolling that scrolled them to a position that centered a card. If your curious I might be able to throw up a Gist in a day or two with that code.

**Comment by rogerkerse** [comment]
@RubenSandwich would be interested in the Gist :)

**Comment by RubenSandwich** [comment]
@rogerkerse 

Here is the Swiper Component gist:
https://gist.github.com/RubenSandwich/8b51c5cf188575844a2a0917fca3ac02

And an example on how to use it:
https://gist.github.com/RubenSandwich/f21beca752ea1d41d5341e9b35352cdd

My team ultimately did not use this code as we run into other problems. Namely:

1. Android has no reliable way to set ScrollView's initial contentOffset.
2. contentOffset does not work with a ListView when your initial card is past the page size. (And we needed a ListView because of the number of cards we need.)

Those problems led us to ultimately pursue a different direction so the above code never saw production. But consider the gists to be MIT licensed, so feel free to use it in whatever way you want.

**Comment by dwilt** [comment]
@RubenSandwich Yep, totally understand your points. For Android, we'll be implementing the overflow and aren't using `zIndex` so that's not a sacrifice that kills us. And our users have run into the issue of swiping from the far left and right and thus it not working (as you pointed out) which sucks. I'll report back here if I ever solve or find a better solution.

**Comment by grundmanise** [comment]
@RubenSandwich have you tried to implement [this ](http://stackoverflow.com/a/1220605/4541800) from the native side?

**Comment by tdurand** [comment]
Hi there, 

I'm trying to make the overflow: visible on the Swiper component on Android even knowing the drawbacks, with react native 0.41.2 , but it doesn't seem to work. 

Any of you succeeded to make it work ?

**Comment by saurabhsg83** [comment]
@tdurand  doing it on 0.42.3, not working for me either.
@RubenSandwich, @robbue , @dwilt  is there any solution for android for partial visibility of swiper?

**Comment by andrispraulitis** [comment]
@saurabhsg83 yes there is: https://github.com/archriss/react-native-snap-carousel

**Comment by adarshTS** [comment]
Can someone help me with this
[https://stackoverflow.com/questions/45568086/how-to-select-the-center-item-in-a-scroll-view-from-a-list-of-items](https://stackoverflow.com/questions/45568086/how-to-select-the-center-item-in-a-scroll-view-from-a-list-of-items)

**Comment by madebyrobin** [comment]
I've just been battling with this myself, so in case anyone else finds themselves in this scenario, I ended up using React Native's default `FlatList` instead and found it much easier to do what I wanted:

```
        <FlatList
          data={this.state.cards}
          renderItem={this._renderCard}
          pagingEnabled={true}
          horizontal={true}
          onViewableItemsChanged={this.onViewableItemsChanged}
          viewabilityConfig={this.viewabilityConfig}
          showsHorizontalScrollIndicator={false}
          decelerationRate={0}
          snapToInterval={Dimensions.get("window").width - 60}
          snapToAlignment={"center"}
          centerContent={true}
          contentInset={{
            top: 0,
            left: 30,
            bottom: 0,
            right: 30
          }}
        />
```

**Comment by wyrustaaruz** [comment]
also you can use this lib.
https://www.npmjs.com/package/react-native-snap-carousel

**Comment by nghiemtien** [comment]
using props : scrollViewStyle={{overflow: 'visible'}} removeClippedSubviews={false} containerStyle={{ width: 300 }}

**Comment by KYesmine** [comment]
Thank you [nghiemtien](https://github.com/nghiemtien), works perfectly for me 👍

**Comment by divyenduz** [comment]
✅

**Comment by Emmanuel0705** [comment]
> @saurabhsg83 yes there is: https://github.com/archriss/react-native-snap-carousel

this works

**Comment by dogukanakkaya** [comment]
Is there any way for this to work with `cssMode: true`. It adds `overflow: auto` and changing that breaks the scroll snap.
