### ISSUE TITLE
can it used on web？

### ISSUE THREAD

**Issue by damiaozi** [leecade/react-native-swiper#455]
can it used on web？

**Comment by mrdezzods** [comment]
No, this is a package for react native and won't work on web.

**Comment by notgiorgi** [comment]
Would this work with react-native-web?

**Comment by jtormey** [comment]
If you add a check for `Platform.OS === 'web'` [here](https://github.com/leecade/react-native-swiper/blob/8b29dec0177541d6465add9897a4f4546fe7b768/src/index.js#L574) then it will render on web (using react-native-web). However it doesn't work very well, since rn-web doesn't seem to support many of the iOS-only ScrollView properties.
