### ISSUE TITLE
Git repo is ahead of npm module and non-functional

### ISSUE THREAD

**Issue by rreusser** [leecade/react-native-swiper#48]
Please correct me if I'm wrong, but it appears that a recent commit has made the swiper non-functional. The npm module is dated '5 months ago', but there are a number of commits past that on the master github branch. My slides just stack vertically instead of being swipeable. Is it possible or reasonable to move recent commits to a branch and sync the master branch with what's on npm?

**Comment by grabbou** [comment]
I think the latest commit to `rewrite` navigation and buttons broke the app completely and it also prints warnings about react keys. Here's the fork I am using in my apps https://github.com/manandmoon/react-native-swiper. It's not in the NPM, so you need to specify github path instead of version, but if the current package is no longer maintained, I will need to republish under another name.

**Comment by rreusser** [comment]
Sounds good! It works great overall, so I imagine this will be getting more traffic instead of less as react-native continues to consume the world. So maybe this'll just serve as a sign post. I'll submit PRs to the other repo, and maybe at some point we can regroup and sync into master.

**Comment by grabbou** [comment]
Yep, that's my hope too, sounds like `node` and `io` hehe. Generally the roadmap for the fork is to do all the things that are listed in `todo` section, specifically examples running on new React, better build process, eslint, code refactor & clean up.

**Comment by leecade** [comment]
published a new version, sorry for so later
