### ISSUE TITLE
resize height in method onLayout is not correctly

### ISSUE THREAD

**Issue by engin145** [leecade/react-native-swiper#491]
When change orientation landscape -> portrait -> landscape,  have next value height 
519 -> 271 -> 271

v.1.5.7

**Comment by RavishankarR** [comment]
Having same issue. Both height and width does not change upon orientation.

**Comment by soundstage** [comment]
It can be fixed by calling onLayout method on the swiper itself.

onLayout(e){
const{width, height}=Dimensions.get('window');
this.setState({
windowHeight: height,
windowWidth: width
});
this.forceUpdate();
}

<Swiper width={this.state.windowWidth} height={this.state.windowHeight} onLayout={this.onLayout.bind(this)}>
...
...
<Swiper>

**Comment by mrdezzods** [comment]
@soundstage can you please a merge request with the fix if possible? Thanks

**Comment by engin145** [comment]
Fixed in v.1.5.10
