### ISSUE TITLE
undefined is not an object (evaluating '_this.state.offset[dir]')

### ISSUE THREAD

**Issue by xiaomlove** [leecade/react-native-swiper#501]
react-native-cli: 2.0.1
react-native: 0.46.3
"react-native-swiper": "^1.5.7",
"react-native-photo-view": "^1.3.0",

I copy the the code of demo: [PhotoView](https://github.com/leecade/react-native-swiper/blob/master/examples/components/PhotoView/index.js)

when swipe to the edge, it goes wrong, what's the problem ?

![2017-08-10 12 02 30](https://user-images.githubusercontent.com/8530353/29131438-7a846a62-7d5f-11e7-9435-d4e1c63d82b7.png)

**Comment by mtt87** [comment]
+1 
Basically when you reach the end of the loop it crashes with that error

**Comment by mtt87** [comment]
I can also confirm this is working fine in version `1.5.5` and not working with `1.5.7` and `1.5.8` so the problem has been introduced in `1.5.7`

**Comment by mtt87** [comment]
https://github.com/leecade/react-native-swiper/compare/1.5.5...1.5.7

**Comment by mrdezzods** [comment]
@arribbar Can you dig into this?
I tried the examples in my laptop on IOS emulator and all the examples work fine. Even if I swipe from the edges.

**Comment by xiaomlove** [comment]
I update to version 1.5.8, and it works fine, cheers!

**Comment by 532878340** [comment]
WTF! I did nothing but it's ok now~~~~~~

**Comment by mtt87** [comment]
It's not crashing but it doesn't work properly.
![giphy 1](https://user-images.githubusercontent.com/2150927/29210466-0554e24a-7e94-11e7-981f-ec69457f42aa.gif)

Example of a swiper with infinite loop, 3 images and 3 dots:
When you do a swipe on the left to move to the second image, the dot is not changing.
When you swipe again on the left to move to the third image, the dot is changing to position 2.
When you swipe again you are at the initial image but the dot is on position 3 instead of 1.

It's not crashing but doesn't work properly.

**Comment by 532878340** [comment]
Thanks，i've got it. On 2017-08-11 18:53 , Mattia Asti Wrote: It's not crashing but it doesn't work properly. Example of a swiper with infinite loop, 3 images and 3 dots: When you do a swipe on the left to move to the second image, the dot is not changing. When you swipe again on the left to move to the third image, the dot is changing to position 2. When you swipe again you are at the initial image but the dot is on position 3 instead of 1. It's not crashing but doesn't work properly. — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by arribbar** [comment]
@mtt87 Can you create a new issue please with your bug?
Can you add some infos as OS platform, RN version, RN Swiper version. If you could add an example of your code in which we can reproduce the bug, it would be great. You can fork the project and change one example to do so.
Thanks !

**Comment by arminsal1** [comment]
I'm having the same runtime error on 1.5.12. Did we come to a solution?
