### ISSUE TITLE
Android Swiper showing item during swiping 

### ISSUE THREAD

**Issue by Jacky9425** [leecade/react-native-swiper#908]
### Version
Which versions are you using:

- react-native-swiper v1.5.14
- react-native v0.57.2

### Expected behaviour
Swipe smoothly every item contained.

### Actual behaviour
Swipe and item showed at the left/right side during swiping. Seeing the item appears before the swipe is complete

### How to reproduce it>
reduce the container to be smaller instead of full screen.

```
<Swiper containerStyle={{height:60,width:155,alignSelf:'center'}} autoplay height={60} width={150} style={styles.wrapper} showsButtons showsPagination={false}>
        <View style={styles.slide1}>
            <Text style={styles.text}>Hello Swiper</Text>
         /View>
        <View style={styles.slide2}>
            <Text style={styles.text}>Beautiful</Text>
        </View>
        <View style={styles.slide3}>
            <Text style={styles.text}>And simple</Text>
        </View>
</Swiper>
```

**Comment by mohsinnaqvi110** [comment]
Yes? Any solution please share.

Facing the same problem

**Comment by mohsinnaqvi110** [comment]
@Jacky9425 any luck with this problem?

**Comment by Jacky9425** [comment]
im using another package. The source code for this package is using `ViewPagerAndroid` on android device and `ScrollView `on IOS. `ViewPagerAndroid `is behaving as previewing the next/previous screen during swiping. You can try `react-native-looped-carousel` instead.

**Comment by mohsinnaqvi110** [comment]
Btw I just fix the problem:

My problem was when i try to swipe the slider (child of swiper) image and it is not full width (Means slider (child of swiper)  has margins from left/right). It shows images while swiping on left/right

Solution:
Instead of adding margins/padding inside child of swiper make it in parent layout. It will fix the problem.
Because i think when ViewPagerAndroid swipe happens it make it full parent width so that glitch is visible.

**Comment by Jacky9425** [comment]
because my parent layout is not covering full device so it is very frustrating seeing image previews before the swiping is finished. Anyway thank you for you advice.
